// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RouteService.Data.Databases;

#nullable disable

namespace RouteService.Data.Migrations
{
    [DbContext(typeof(AppDatabase))]
    partial class AppDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RouteService.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("CoordinatesStart")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Point>("CoordinatesStop")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DriverVehicleId")
                        .HasColumnType("uuid");

                    b.Property<double>("EstimatedDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("EstimatedFuelConsumptionLiters")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("RealDistanceKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("RealFuelConsumptionLiters")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesStart");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CoordinatesStart"), "GIST");

                    b.HasIndex("CoordinatesStop");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CoordinatesStop"), "GIST");

                    b.ToTable("Routes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
