services:
  normaldb:
    container_name: ad-pf-db
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clave_piola
      POSTGRES_DB: proyecto-distribuidas
    volumes:
      - ./data/postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - adpfnetwork

  eureka:
    container_name: ad-pf-eureka
    image: steeltoeoss/eureka-server # Imagen funcional de Eureka OSS
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: "false"
    networks:
      - adpfnetwork

  gateway:
    container_name: ad-pf-gateway
    image: aparedeslozada/ad-proyecto-final-gateway:3
    restart: unless-stopped
    depends_on:
      - eureka
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      FRONTEND_ORIGIN: http://localhost:5173
      DRIVER_PROTO_PATH: /app/Protos/drivers.proto
      VEHICLE_PROTO_PATH: /app/Protos/vehicles.proto
      JWT_SECRET: b674d61f8fa4763520494479868548fc0fa05e571b8103e96bdcabaeddf51473
      JWT_ISSUER: http://authservice:5121
      APP_NAME: api-gateway
      HOST: gateway
      IP: 0.0.0.0
      EUREKA_HOST: eureka
      EUREKA_PORT: 8761
    networks:
      - adpfnetwork

  authservice:
    container_name: ad-pf-auth-service
    image: aparedeslozada/ad-proyecto-final-auth-service:7
    restart: unless-stopped
    depends_on:
      - normaldb
      - eureka
    ports:
      - "5121:5121"
      - "7037:7037"
    environment:
      JWT_SECRET: "b674d61f8fa4763520494479868548fc0fa05e571b8103e96bdcabaeddf51473"
      JWT_ISSUER: "http://authservice:5121"
      JWT_TIME: "2"
      HTTP1_PORT: "5121"
      HTTP2_PORT: "7037"
      CONNECTION_STRING: "Host=normaldb;Port=5432;Database=proyecto-distribuidas;Username=postgres;Password=clave_piola"
      SEQ_URL: "http://host.docker.internal:5341"
      # Eureka interno por Docker
      eureka__client__serviceUrl: "http://eureka:8761/eureka"
      eureka__instance__hostName: "authservice"
      eureka__instance__appName: "AUTH-SERVICE"
      eureka__instance__port: "7037"
      eureka__instance__metadataMap__httpPort: "5121"
      eureka__instance__metadataMap__grpcPort: "7037"
    networks:
      - adpfnetwork
  
  vehicleservice:
    container_name: ad-pf-vehicle-service
    image: aparedeslozada/ad-proyecto-final-vehicle-service:5
    restart: unless-stopped
    depends_on:
      - normaldb
      - eureka
    ports:
      - "5124:5124"
    environment:
      JWT_SECRET: "b674d61f8fa4763520494479868548fc0fa05e571b8103e96bdcabaeddf51473"
      JWT_ISSUER: "http://authservice:5121"
      JWT_AUDIENCE: "http://authservice:5121"
      JWT_TIME: "2"
      PORT: "5124"
      CONNECTION_STRING: "Host=normaldb;Port=5432;Database=proyecto-distribuidas;Username=postgres;Password=clave_piola"
      SEQ_URL: "http://host.docker.internal:5341"
      # Eureka interno por Docker
      eureka__client__serviceUrl: "http://eureka:8761/eureka"
      eureka__instance__hostName: "vehicleservice"
      eureka__instance__appName: "VEHICLE-SERVICE"
      eureka__instance__port: "5124"
      eureka__instance__preferIpAddress: true
    networks:
      - adpfnetwork

  adminservice:
      container_name: ad-pf-admin-service
      image: aparedeslozada/ad-proyecto-final-admin-service:1
      restart: unless-stopped
      depends_on:
        - normaldb
        - eureka
      ports:
        - "5123:5123"
        - "7039:7039"
      environment:
        AUTH_AUTHORITY: "http://authservice:5121"
        HTTP1_PORT: "5123"
        HTTP2_PORT: "7039"
        SEQ_URL: "http://host.docker.internal:5341"
        # Eureka interno por Docker
        eureka__client__serviceUrl: "http://eureka:8761/eureka"
        eureka__instance__hostName: "adminservice"
        eureka__instance__appName: "ADMIN-SERVICE"
        eureka__instance__port: "7039"
        eureka__instance__metadataMap__httpPort: "5123"
        eureka__instance__metadataMap__grpcPort: "7039"
      networks:
        - adpfnetwork
  
  driverservice:
    container_name: ad-pf-driver-service
    image: aparedeslozada/ad-proyecto-final-driver-service:1
    restart: unless-stopped
    depends_on:
      - normaldb
      - eureka
    ports:
      - "5122:5122"
    environment:
      JWT_SECRET: "b674d61f8fa4763520494479868548fc0fa05e571b8103e96bdcabaeddf51473"
      JWT_ISSUER: "http://authservice:5121"
      JWT_AUDIENCE: "http://authservice:5121"
      PORT: "5122"
      CONNECTION_STRING: "Host=normaldb;Port=5432;Database=proyecto-distribuidas;Username=postgres;Password=clave_piola"
      SEQ_URL: "http://host.docker.internal:5341"
      # Eureka interno por Docker
      eureka__client__serviceUrl: "http://eureka:8761/eureka"
      eureka__instance__hostName: "driverservice"
      eureka__instance__appName: "DRIVER-SERVICE"
      eureka__instance__port: "5122"
      eureka__instance__preferIpAddress: true
    networks:
      - adpfnetwork
    
  
networks:
  adpfnetwork:
    driver: bridge
