services:
  coordinator:
    image: citusdata/citus:latest
    container_name: citus_coordinator_ad
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: proyecto-distribuidas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clave_piola
    volumes:
      - ./volumes/coordinator:/var/lib/postgresql/data
      - ./init/coordinator:/docker-entrypoint-initdb.d
    depends_on:
      worker1:
        condition: service_healthy # <-- IMPORTANTE
      worker2:
        condition: service_healthy # <-- IMPORTANTE
    networks:
      - citus_network
    # Opcional: healthcheck para coordinador
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker1:
    image: citusdata/citus:latest
    container_name: citus_worker1_ad
    restart: unless-stopped
    environment:
      POSTGRES_DB: proyecto-distribuidas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clave_piola
    volumes:
      - ./volumes/worker1:/var/lib/postgresql/data
      - ./init/worker:/docker-entrypoint-initdb.d
    networks:
      - citus_network
    # AÑADIR HEALTHCHECK
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker2:
    image: citusdata/citus:latest
    container_name: citus_worker2_ad
    restart: unless-stopped
    environment:
      POSTGRES_DB: proyecto-distribuidas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clave_piola
    volumes:
      - ./volumes/worker2:/var/lib/postgresql/data
      - ./init/worker:/docker-entrypoint-initdb.d
    networks:
      - citus_network
    # AÑADIR HEALTHCHECK
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
networks:
  citus_network:
    driver: bridge
