services:
  postgres_master:
    container_name: postgres_master
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=clave_piola
      - POSTGRESQL_DATABASE=proyecto-distribuidas
      - POSTGRESQL_REPLICATION_USER=user_r
      - POSTGRESQL_REPLICATION_PASSWORD=clave_piola
    volumes:
      - ./volumes/master:/bitnami/postgresql
    networks:
      - rep_postgres
  postgres_slave1:
    container_name: postgres_slave1
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=clave_piola
      - POSTGRESQL_DATABASE=proyecto-distribuidas
      - POSTGRESQL_MASTER_HOST=postgres_master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=user_r
      - POSTGRESQL_REPLICATION_PASSWORD=clave_piola
    depends_on:
      - postgres_master
    volumes:
      - ./volumes/slave1:/bitnami/postgresql
    networks:
      - rep_postgres

networks:
  rep_postgres:
    driver: bridge
